export class IdRequest{
    id:number;
    idservice:string;
    username:string;
    password:string;
    firstName:string;
    lastName:string;
    email:string;
    tel:string;
    gender:string;
    remark:string;
    department:string;
    mobileNo:string;
    subsidiaryId:string;
    DateofJoin:Date;
    existedUserId:number;
    employeeName:string;
    createUser:string;
    loginName:string;
}